# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all 

user1 = User.create!(username: "Eli", password: "password") 

file = File.open('app/assets/images/88.jpg')
user1.image = file
user1.save!

user2 = User.create!(username: "Jim", password: "password") 

file = File.open('app/assets/images/58.jpg')
user2.image = file
user2.save!

user3 = User.create!(username: "Davis", password: "password") 

file = File.open('app/assets/images/40.jpg')
user3.image = file
user3.save!

user4 = User.create!(username: "Michelle", password: "password")

file = File.open('app/assets/images/43.jpg')
user4.image = file
user4.save! 

user5 = User.create!(username: "Rachel", password: "password") 

file = File.open('app/assets/images/26.jpg')
user5.image = file
user5.save!

user6 = User.create!(username: "Betty", password: "password") 

file = File.open('app/assets/images/21.jpg')
user6.image = file
user6.save!

user7 = User.create!(username: "Guest", password: "password")
user8 = User.create!(username: "Gabby", password: "password")

file = File.open('app/assets/images/71.jpg')
user8.image = file
user8.save!

Story.destroy_all

story1 = Story.new(title: "Our first story", category: "General", body: "<p>Once upon a time, Medio was born</p>", author_id: user1.id)

file = File.open('app/assets/images/medio.jpg')
story1.image = file
story1.save!

comment1 = Comment.create!(body: "our first comment", author_id: user2.id, story_id: story1.id)
comment2 = Comment.create!(body: "our second comment", author_id: user2.id, story_id: story1.id)
comment3 = Comment.create!(body: "our third comment", author_id: user2.id, story_id: story1.id)
comment4 = Comment.create!(body: "our fourth comment", author_id: user2.id, story_id: story1.id)
comment5 = Comment.create!(body: "our fifth comment", author_id: user2.id, story_id: story1.id)

story2 = Story.new(title: "Drawing the Eclipse", category: "Science", body: "<p>Today I drew the eclipse for CBS News in NY City, and while not a totality zone (love that phrase, which means a place where you can experience a full eclipse. NYC was about 75%), it didn’t matter to me. I was happy to be able to cover and draw the city I love so much, to draw New Yorkers as they gathered to gaze skyward. I was stationed at the American Museum of Natural History, where they held an “event” on their Hayden Planetarium terrace (a homecoming of sorts for me: my first job in NYC was in the art department of the museum).\n 
People were in a friendly, exited, chatty mood. I spent most of the time watching people, although I did put on my eclipse glasses three times to view the sun/moon; frankly I found the people more interesting. But the mood was unique: there were oos and aahs, and clapping at times. As I watched and drew the gathered group around me, what I felt was comaraderie, a relief to be spending time together doing something that was not about politics or feeling divided as a country. Perhaps that’s my spin. But nonetheless, it was wonderful to see such a diversity of people come out to watch the eclipse — the very young and the very old, and many, many different races.</p>", author_id: user5.id)

file = File.open('app/assets/images/eclipse.jpg')
story2.image = file
story2.save!

story5 = Story.new(title: "Palermitano or Romano?: Problems of Chronology and Documentation", category: "Art", author_id: user8.id, body: "<p>Michelangelo Merisi da Caravaggio’s Nativity with Saints Lawrence and Francis, formerly the central altarpiece of Palermo’s Oratory of San Lorenzo, was stolen on the night or early morning of October 17-18, 1969.  Thieves entered the unlocked oratory under cover of darkness and, through a combination of cutting with razors and brute force, ripped the canvas from its frame. Recently, a Mafia pentito (turncoat) testified in court that the Nativity was hidden in a shed in rural Sicily, where the painting was so severely damaged by vermin that its owners ordered its destruction.  Allegedly, the painting was burned, and it remains unlikely that the picture will be recovered through legal investigation.\n 
Regardless of the Nativity’s fate, it has become the fixation of recent scholarship on Caravaggio. There is a vigorous controversy brewing on the dating of the picture. Several scholars have proposed to re-date the Nativity to 1600 Rome, challenging the long-held consensus that Caravaggio painted the altarpiece in Palermo in 1609 on the last leg of his Sicilian sojourn. Revising the chronology of Caravaggio’s paintings, especially his late works, could potentially alter our understanding of his stylistic development. This paper, thus, will carefully consider the arguments for the Palermo Nativity’s early (1600) and late (1609) chronological assignments and, based on extant documentary, literary, and visual evidence, concludes that the Nativity was likely painted in Sicily in the summer of 1609. The Palermo Nativity shares greater formal similarities with works from Caravaggio’s second visit to Naples, circa 1609-1610, than with those, as proposed by scholars attempting to re-date the picture, of Caravaggio’s mature Roman period, circa 1600-1601. Additionally, the re-dating hypotheses fail to consider Caravaggio’s creative process, namely his ability to adapt to the specific requests of patrons and to recycle, in his later works, figural types and themes from earlier in his career.\n 
Most art historians rely on the accounts of Caravaggio’s seicento and settecento biographers to reconstruct the chronology of his works and understand the trajectory of his career. Of Caravaggio’s biographies, the most informed and pertinent to the Nativity are the vite of Giovanni Baglione (1642), Giovan Pietro Bellori (1672), and Francesco Susinno (1724). Each author writes that Caravaggio visited Palermo, but only Bellori offers a full description of the Nativity and provides the painting’s location in the Oratory of San Lorenzo.\n 
In 1951, Roberto Longhi, a respected early voice in Caravaggio studies, dated the Palermo Nativity to the summer of 1609 based largely on Bellori’s account, surviving archival materials, and the painting’s style. Unlike Longhi, some modern scholars active throughout the twentieth-century have questioned a 1609 date for the Nativity due to its stylistic differences from Caravaggio’s other Sicilian works.  Many of these arguments for giving the Nativity an early Roman period date never gained widespread support in the art-historical community. The vast majority of experts in the field follow Longhi’s lead and believe the narrative forged by Bellori, which places the Nativity in the summer of 1609. Since proposals to re-date the Nativity resurfaced in 2011, more experts, such as Richard Spear and Keith Christiansen, are beginning to accept the possibility of the painting’s earlier date. Considering the frequency with which scholars are beginning to challenge Longhi’s original dating of the Nativity, it is crucial to dive deeply into the documentary and stylistic arguments for a re-dating to assess their legitimacy.\n 
The Fabio Nuti document is central to recent scholarship attempting to re-date the Palermo Nativity to 1600. The notarized contract, dated 5 April 1600 and discovered in the Roman State Archives, offers precious little information about the commission.  Approximate dimensions are estimated in Roman palmi, twelve palmi in height (268 cm) and seven or eight palmi in length (156-180 cm), a standard size for an altarpiece, yet the subject is not described. The contract vaguely mentions that the intended painting would contain figures. The completed work was expected by mid-June 1600, seventy days after the signing of the agreement. Upon receipt of the painting, Caravaggio would be paid a total of two hundred scudi, sixty of which were paid up front on April 5, the day the contract was notarized. A second document, dated 20 November 1600, records the painting’s delivery and Caravaggio’s payment, albeit several months after the June deadline.\n
No subject is given in either document and a final destination for the canvas is not specified; only the dimensions for the prospective picture are provided in the contract, leaving the iconography open for art-historical guesswork. Since the contract’s discovery in 1971, many scholars have proposed previously undocumented works as candidates for the Nuti commission; Alfred Moir was the first to suggest the Nativity as the Nuti painting in 1982. Analyzing the painting’s price, Catherine Puglisi does not propose a specific painting as the work ordered by Nuti, but suggests that the “respectable fee” of two hundred scudi stipulated in the contract could imply that the Nuti painting was a public commission.  Other payments Caravaggio received circa 1600 in Rome for the Contarelli and Cerasi chapel laterals support this claim. These two famous public commissions are roughly contemporaneous with the Nuti painting, and their similarity in prices could indicate that the Nuti work was intended for a Roman church.\n 
Other scholars have attempted to explain the vagueness of the Nuti document. Maurizio Marini suggests the contract was created as the final part of a series of private negotiations between Caravaggio, Fabio Nuti, and Nuti’s appointed artistic committee.  Marini’s reading also implies that the committee came to an informal agreement for the painting and may have drafted the notarized contract as a legal formality to ensure each party was protected, in the artist’s compensation for his work and the delivery of the painting to the commissioner. As everyone involved with the commission was already familiar with its subject, final destination, and terms, there would have been no need to list specifics, beyond the agreed payment and expected delivery time, in the contract.\n
Giovanni Mendola revisited the Nuti document in 2012, identifying the Palermo Nativity as the contract’s painting. His argument is driven by Caravaggio’s nonexistent archival record in Palermo, and, in his opinion, the Nativity’s significant stylistic differences from the other Sicilian altarpieces. Mendola’s archival research in Palermo suggests that the Oratory of San Lorenzo underwent successive renovations in the last decades of the cinquecento and throughout the seicento, and Mendola suspects that an altarpiece would have been commissioned in the jubilee year to be placed in time for St Lawrence’s feast day on 10 August. He attempts to build a network of connections between Caravaggio and his artistic sphere in Rome, members of the Company of St Francis, and Fabio Nuti in order to explain why an Oratory in Palermo would commission a painting from Caravaggio in Rome in 1600.\n 
Mendola’s discovery of a recorded payment, dating to 28 July 1600, for a gilded frame for the high altar of the Oratory fuels his re-dating of the Nativity.  Despite the fact that the contents of this frame and its dimensions are not explicitly stated in the payment receipt, he argues with little supporting evidence that the frame was commissioned exclusively for the Nativity in advance of its arrival in Palermo, and prompts the reader to doubt that a newly renovated oratory would wait nine years—until 1609—for a new altarpiece after already purchasing a frame.  However, the receipt for the gilded frame precedes the second Nuti document recording the painting’s delivery by over three months. It is unpractical, and unlikely, that the Oratory would order a frame specifically for the Nativity without the painting having been completed or already in Palermo.\n 
A more convincing alternative is that the Oratory installed a work in situ on their high altar before the placement of Caravaggio’s Nativity in 1609. Local Sicilian painters who had already frescoed the interior of the Oratory could have painted an altarpiece that was placed before St Lawrence’s feast day on 10 August 1600. This proposal aligns with the 28 July date on the receipt for the gilded frame. Since the Oratory underwent repeated renovations, it is possible that in 1609 Caravaggio’s Nativity replaced the painting originally intended for the gilded frame.\n
  Mendola’s reconstruction of Caravaggio’s social network relies upon undocumented and speculative interactions between members of the Roman confraternity of Santa Maria Odigitria dei Siciliani, Sicilian artists active in Rome, and Caravaggio in order to explain why Nuti commissioned a painting from Caravaggio in 1600 for the Oratory of San Lorenzo in Palermo. Without supporting documentary evidence, it is impossible to reconstruct concrete relationships to convincingly argue that the Nativity is the Nuti painting from 1600.\n
Scholars dating the Nativity to the summer of 1609 tend to approach Caravaggio’s Sicilian works as a cohesive group because according to Bellori and the remaining archival evidence, they were painted within the span of approximately one year. Although the four altarpieces are understood as a product of Caravaggio’s artistic activity on the island, many scholars note that the Palermo Nativity is an outlier stylistically. The Syracuse and Messina altarpieces adhere to a new compositional device Caravaggio developed in Malta, where he began to situate his figures farther away from the picture plane underneath large recesses of empty space.  The pictorial narrative in the Burial of St Lucy, the Raising of Lazarus, and the Adoration of the Shepherds is confined to the bottom portion of the composition; with the exception of the gravediggers in the Burial of St Lucy, the figures in each of these paintings are placed far from the picture plane, emphasizing the scale of the ill-defined setting in each image. The Nativity, in contrast, does not feature a significant area of space above its figures. Instead they form a circle, seated and standing, around the newly born Christ child lying unadorned in the hay; their arrangement produces radial diagonals that direct attention to the divine baby.</p>   
")

file = File.open('app/assets/images/CaravaggioNativity.png')
story5.image = file
story5.save!

story3 = Story.new(title: "Where does it come from?", category: "General", author_id: user2.id, body: '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>')

file = File.open('app/assets/images/Latin.jpg')
story3.image = file
story3.save!

story4 = Story.new(title: "The Pleasures Of New York By Car", category: "General", author_id: user3.id, body: "<p>My two cars have enough miles between them to circle the earth ten times at the equator. I prefer the older one, a 2000 Honda Civic that used to belong to my mother-in-law. It has racked up most of its miles in New Jersey, where I live, and in New York City. Nothing about it stands out—not its tan color, or its shape, or the small yellow-and-white 2004 parking decal from the College of Staten Island on its left rear window. If you asked people to draw a car, my Honda is probably about what they would come up with. It has been through a lot. Last year, while driving absent-mindedly, I let it get overheated. I had not paid attention to the greenish stain on the pavement where I parked it. All the coolant had leaked out through a hole in the radiator. I started smelling strange smells, steam and smoke came from under the hood, and I pulled over next to a Baptist church on Route 3 whose occupants immediately emerged to ask if they could help. I had “melted” the engine, my mechanic said later; extreme heat had wrecked it beyond repair. He put in a used engine to replace it.\n 
In eighteen years, the car’s exterior has accumulated some dents. I haven’t noticed them, growing accustomed to them over time. The result is that the car looks different to me from the way it does to other people, just the way my face looks different in my bathroom mirror from the way it does in the security photos of me that the staff behind front desks take before I go into office buildings in Manhattan. I mean that I do not think of my car as a junker.\n 
Recently, I was in a seven-car pileup on the Garden State Parkway. No one was badly hurt, though the multiple collisions totalled several cars. I got hit on the left rear bumper, which was smashed in, along with the tail-light. The plastic part of the bumper was hanging down. A state policeman who assessed the various damages came over to my Honda with his clipboard. He walked around the car, taking it all in. Then he stopped at the trashed bumper, pointed to it and the tail-light, and asked, “Was it like this before?”\n 
Some people say that they hate to drive in the city and that driving in New Jersey is even worse. It’s true that New Jersey can be a bit of a puzzle. I think the state has decided that providing the kind of road signs that actually explain where you should go would do more harm than good, slowing traffic flow at crucial junctures. So the policy seems to be that the driver will learn by trial and error. In complicated places, of which there are many, you make the mistake once or twice or three times and then you learn. The misconception people have about driving in New Jersey is that we Jersey drivers think we are driving. In fact, we are swarming. Freeways are nice, but if you have to redirect down a puddled two-lane road between tall reeds that’s fine, too. Anyplace where you can drive is acceptable, basically. And you have to be able to switch quickly from driving-swarming to merely sitting, when you find yourself in a traffic jam. Then it’s best just to chill out, count how many hot, idling trucks within your field of vision have “Logistics” in their company names, and enjoy the temporarily reduced risk of major accident.</p>")

file = File.open('app/assets/images/dropcar.jpg')
story4.image = file
story4.save!

story10 = Story.new(title: "Gustave Caillebotte's Portrait of Henri Cordier", category: "Art", author_id: user8.id, body: "<p>Esteemed scholar Henri Cordier is seated at a handsome chestnut desk in his cramped Parisian study, comfortably leaning over a stack of papers with quill in hand. An immediate intimacy is established with the academic, whose back is partially turned toward the viewer, inviting the eye to look over his left shoulder and into the scene. Cordier’s face is rendered in complete profile and his body is hunched toward the sheet he is writing on, putting his head and chest physically close to his hands as he writes. Cordier’s notes appear blurry and illegible at a distance, but it is understood that his project requires great concentration and thought. His heavy-lidded eyes are cast down, wholly absorbed in his work, as his quill moves across the paper. His greying dark hair and beard appear to be slightly disheveled, as if he recently ran his fingers through his hair in a moment of deep contemplation.\n 
It is a quiet, meditative space. Bookshelves laden with heavy volumes of texts and sets of encyclopedias line the walls, physically surrounding Cordier as he diligently works. To his right, lavishly colored volumes of books fill the shelves and another bookshelf behind the desk, partially hidden by a thick collection of quills, holds even more volumes. The scholar’s grey suit appears to reflect and mimic the vivid reds, greys, blues, and purples of the books, resulting in a reddish-purple tinge emanating from the fabric. The dominant presence of the bookshelves is a testament to Cordier’s career and implies that the literary man is regularly consumed by his scholarship.\n 
The worn black surface of the wooden desk is adorned with a variety of objects, some of which are further signifiers of Cordier’s commitment to his research. Toward the back of the desk, opposite Cordier, is a small faceless military figurine painted in primary colors. Barely discernable, its uniform is composed of a navy blue jacket and red underclothes, and the figure is armed with a golden spear, shield, and two-pronged helmet. The figurine is propped against a number of different sized sheets of loose white paper, a large yellowed envelope, and leather bound books. The arrangement of these items in a state of mild disarray suggests that Cordier is often at work in his study and possibly referenced one of these papers or books just moments ago.\n 
Directly behind the papers are two loose bundles of long, cream-colored quills, presumably arranged in containers hidden at the edge of the desk. A highly ornate lamp rests upon the far right corner of the desk, casting a purple shadow onto some of the nearby quills. The lamp’s luminous gold color is intensified by light radiating from its bulb, illuminating a motif of figures carved in low sculptural relief. A fine, elaborate beige fringe hangs from the perimeter of the delicate lace lampshade, almost melding with the adjacent assemblage of quills. The lamp’s light, most importantly, highlights the face of Cordier and the text he is drafting, casting a spotlight on the scholar hard at work in his confined study.
</p>")

file = File.open('app/assets/images/HenriCordier.jpg')
story10.image = file
story10.save!

story11 = Story.new(category: "Art", author_id: user1.id, title: "A Spanish Masterpiece, a Self-Portrait and an Ontological Puzzle", body: "
  <p>After investigating the overwhelming body of scholarly literature that has been written about Velazquez’s Las Meninas (Fig. 1), it is clear that there is no one approach to the painting or interpretation of its significance that scholars have agreed on in the 20th and 21st centuries. Rather, this work of art created in 17th century Spain and housed today in the Museo del Prado in Madrid has been examined in many ways revealing a wide variety of possible meanings. Some examine its iconographical significance and see it as a visual argument for the liberal art of painting as well as an attempt by its painter, Diego Velazquez, to ennoble not just the field of painting, but by extension himself as a friend of the King and an important court official who was seeking membership into the prestigious Order of Santiago. Other scholars observe the painting from a philosophical view focusing on the unique approach to perspective that Velazquez employs in the work. Yet another group of scholars do not focus on examining the painting itself, but rather seek to explore its reception history in Western Europe and the United States during the 19th century.\n 
Nonetheless, one reoccurring theme which a vast majority of scholars all address is the painting’s ability to capture the attention of the viewer and inspire him or her to attempt a new interpretation of the work. Indeed, one of the most fascinating things about reading all of the scholarly literature on Las Meninas is the variety of disciplines that seek to tackle this famous Spanish painting. From Foucault’s philosophical approach, to Hamann’s anthropological study to Brown’s art historical discussion, it is clear that the painting does not only belong to the field of art history. Interestingly enough, none of these authors view their own interpretations as sufficient and instead acknowledge that the work cannot be explained in any one analysis. Velazquez specialist, Suzanne Stratton-Pruitt, notes that “there is no last word” on Las Meninas.  While Art Historian, Leo Steinberg, claims that writing about Las Meninas is “somewhat comparable to the performing of a great musical composition of which there are no definitive renderings” viewing his own article as one of an infinite series of scholarly attempts to find meaning in the painting that all result in “guaranteed inadequac(ies).”\n    
Yet it is this continual reinterpretation of the painting, as Jonathan Brown remarks in his essay “On the Meaning of Las Meninas,” that keeps it alive.  To Brown, the painting’s greatest attribute does not lay in any one correct meaning, but rather in its power to be continually viewed by scholars as a masterpiece worthy of further discussion and interpretation. As such, the following essay adds yet another voice to this process of “perpetual revitalization”   of the work by outlining the many and diverse ways in which scholars have constructed meaning in Las Meninas and suggesting ideas for further research and interpretation surrounding this Spanish masterpiece heading into the 21st century.</p>
")

file = File.open('app/assets/images/LasMeninas.png')
story11.image = file
story11.save!

story12 = Story.new(category: "Science", title: "There’s a lot of money up for grabs if you can land (softly) on the moon", author_id: user4.id, body: "<p>If you can send a spacecraft to the moon and loop around our natural satellite one time, or—even better—gently set a rover down on the lunar surface, there could be money in it for you. $4.75 million, to be precise.\n 
  That is, if you happen to be one of the select few finalist teams competing for the Google Lunar XPrize. The awarding organizations—Xprize and Google—have decided to split two prize amounts between whatever teams manage to achieve two distinct feats: \n $1.75 million is up for grabs as part of the Lunar Arrival Milestone Prize. To get a slice of that pie, a “spacecraft must complete one orbit around the moon or enter a direct descent approach to the lunar surface,” according to press materials supplied by XPrize.
A larger chunk—three million dollars—will be split between spacecraft that win the Soft Landing Milestone Prize. To win that, the awarding foundation says that a 'spacecraft must transmit data proving it soft-landed on the lunar surface.'\n 
Both of those achievements must be met before March 31, 2018, which is also the new deadline by which teams must complete their attempt at the $30 million Grand Prize. The Grand Prize goes to the first team that manages to put a robot on the moon, explore for 500 meters, and send high-def images and video back to Earth. There will also be a smaller prize for the second team to meet those goals. The catch? The teams need to be 90 percent privately funded.\n 
Robotic exploration of our solar system has long been the purview of national space agencies, which spend millions, and sometimes billions of dollars on developing new technologies. The Curiosity Rover, for example, cost about $2.6 billion (not a lot when you consider the length of the mission, but still pretty expensive). This competition is an attempt to find cheaper ways of exploring the space around us. Previous privately funded missions, like 4M back in 2014, have been relatively simple in design—and none have landed on the lunar surface.\n 
Five teams so far have secured contracts to launch their spacecraft; SpaceIL, Moon Express, Synergy Moon, TeamIndus, and HAKUTO. They all have official plans to launch something by the end of 2017, which is going to make for an exciting next few months in space news, but they now have a few extra months to complete their mission.
It’s a sweet prize, but getting a share of the money won’t be easy. After all, it actually is rocket science.</p>")

file = File.open('app/assets/images/moon.png')
story12.image = file 
story12.save!

story13 = Story.new(category: "Travel", title: "This 'New' Swiss Hotel Is Actually 140 Years Old", author_id: user3.id, body: "<p>Ninety minutes from Zurich, this hotel and spa is hidden in plain sight.\n
  Switzerland’s storied hotels, while lovely, often blend together in a Swiss-neutral haze. The by-the-numbers rooms in Gstaad and Klosters lean heavily on Alpine nostalgia, while even the splashy lounges in St. Moritz are stocked with hunting lodge armchairs and armoires. But inside one of these grand hotels, you'll find a surprise: the glitziest new resort in the Alps, in a 140-year-old building, no less. \n 
  Located 90 minutes southwest of Zurich amid buttercup fields, pine trees, and concertinaing mountains, the Waldhaus Flims Hotel and Spa went bankrupt in 2015, but American equity investor Z Capital scooped the property up and recently completed its first phase of a $40 million plan to amp up the hotel's luxury. Debuting this past June with little fanfare, the revamped lobby and 142 reimagined rooms now feature bubble lamps, Swiss modern art, and a custom marigold-and-cocoa color palette. The makeover also includes ritzy common rooms, glass-encased fireplaces, a swanky library, and an extensive renovation of the original Belle Epoque pavilion, now home to a ballroom, prosecco bar, and an unapologetically Swiss farm-to-fork restaurant. Specialties include Alpine sturgeon, braised venison, and cheese from the canton of Grisons. (If cheese is really your thing, the hotel also has a restaurant devoted to just that.) Next up? A soon-to-follow medical wellness center.</p>")

file = File.open('app/assets/images/swiss_hotel.jpg')
story13.image = file 
story13.save!

story14 = Story.new(category: "Travel", title: "Why Greece Is Best Seen by Boat
", author_id: user8.id, body: "<p>A traditional Turkish gulet allows a lot of freedom and flexibility.\n 
The summertime appeal of Greece—languid Mediterreanean lunches, charming white-washed villages, hidden swimming coves—can undoubtedly be spoiled by the crowds. But if you look beyond the well- trodden spots (and know how to navigate the Aegean) you’ll happen upon a smattering of tiny isles with all the spoils of the popular spots like Mykonos and Santorini, but without the tourists.\n
Looking to avoid those crowds, my partner and I booked one of the eight cabins aboard Sailing Cruise in Comfort's (SCIC) traditional wooden gulet—two-mast Turkish sailing vessels. Once used for fishing, these boats can now ferry up to 16 passengers for week-long tours through the southern Greek islands and Turkish coastline. The appeal is two-fold: Gulets give you greater access to the more remote islands, since their size allows them to dock in shallower waters, as well as spontaneity—the SCIC itineraries are dictated literally by where the wind blows. “Most other charters in these parts treat their sails as window-dressing,” explains Captain Oktay Yilmaz, “instead relying on their 360-horsepower Diesel engines.” The SCIC sails are raised to catch whatever gust is coming through, so you don’t necessarily know which islands you’ll end up on.\n 
Our first gale (and Yilmaz’s skilled steering) brought us to the Nisyros, home to just over a 1000 residents and one brooding active volcano, Polyvotis. We docked in the sleepy harbor town of Mandraki early enough to watch the local taverna owners open up for the day, and drove up the island’s steep winding roads to the smoldering caldera. According to Greek mythology, Nisyros was once attached to Kos, but Poseidon split the isle in two when a battle between the Gods and the Titans broke out. These days the island is pretty tranquil. Along the crater, the brilliant white-and-blue houses and slumbering tabbys of the tiny village of Nikia serve as the postcard-perfect backdrop for sipping soumada, the traditional Greek almond soft drink served at one of the town's two tavernas.</p>")

file = File.open('app/assets/images/greece.jpg')
story14.image = file 
story14.save!

story15 = Story.new(category: "Food", title: "How and Where to Fika in Stockholm
", author_id: user6.id, body: "<p>The city is the capital of the coffee break.\n 
Fika, or the act of taking a break over coffee and a snack, is a Swedish tradition that, at its roots, encourages people to pause and reset. Contrary to grabbing a cup of joe to go, in Sweden, fika is a time where you're obliged to forget everything, at least for a little while, and savor the present—preferably over a piping-hot cup of coffee.\n 
“It’s the moment of the day you share with someone you really like or someone you want to know better,” says Arman Seropian, co-owner of Café Pascal in Stockholm.\n 
Sweden consumes 18 pounds of the stuff per capita, per year—about 864 cups a person. But just as important as the drinks are the treats that are paired with them, which can range from classic Swedish pastries like kanelbulle (a twisty cinnamon bun sans frosting), chokladboll (an uncooked chocolate ball rolled in coconut flakes), and semlor (a cream puff-like bun filled with fluffy marzipan and whipped cream), to trendy, more savory treats like avocado toast.\n 
The crucial thing about fika, though, is that you make time to slow down. Swedes fika (it’s a verb and a noun) most commonly around 11 a.m., but can fika several times a day—yes, even during the work week. They may be on to something: According to the United Nations' 2017 World Happiness Report, Sweden ranks in the top ten countries whose inhabitants are happiest (and friendliest).\n 
Stockholm in particular is home to hundreds of uber-stylish cafes whose Scandinavian design is often part of their draw, especially for tourists. “For us, [the aesthetic and design] is super important as that’s part of the vibe you sense when you enter the café,” says Seropian, though Green Rabbit chef Mathias Dahlgren is quick to point out that the focus is really about “a good cup of coffee and sitting down for a couple of minutes with friends, family, and co-workers.” Unsurprisingly, both cafés have seen in an increase in foreign visitors who are eager to try out fika for themselves.</p>")

file = File.open('app/assets/images/fika.jpg')
story15.image = file 
story15.save!

story16 = Story.new(category: "Food", title: "Why You Should Eat Rice—Not Pasta—in Milan", author_id: user4.id, body: "<p>Where to eat the classic risotto alla Milanese in Milan, plus, what to avoid.\n
Many travelers immediately think of Italy as the land of pizza, pasta and hunks of fresh cheese, but it actually produces the lion’s share of Europe’s rice—and has quite a history with it. The grain first surfaced in Italy in the 13th century via the conquering Moors, who introduced it to Sicily. From there, the crop made its way to Naples and the ruling family then sent it north, to be harvested in the Po Valley, near Milan. In the “rice bowl of Italy,” the grain grows easily thanks to higher humidity, lots of water, and a flat landscape.\n “The Milanese have perfected a way to cook the rice, which is the risotto. Growing up, it was always on the table,” Andrea Oschetti, the Milanese chef behind Blueflower experiential food and travel service, tells Condé Nast Traveler. 'If you pay close attention to the simplicity and quality of ingredients of a good risotto, you can understand the essence of the culture.'\n 
Made with vibrant yellow saffron and bit of bone marrow for good measure, risotto alla Milanese is a staple on traditional menus. While ubiquitous now, it was actually invented on a whim. During the construction of the Milan Cathedral in the 16th century, a cook is said to have added saffron to mimic the sunny stained glass windows...and it stuck.\n 
“This is a simple dish to make—all you need is a great broth, rice, Parmesan cheese, and some butter. But the fundamental for a traditional risotto alla Milanese is bone marrow,” says Oschetti. 'Just a little bit. Not a lot. It gives the taste a kick.'</p>")

file = File.open('app/assets/images/riso.jpg')
story16.image = file 
story16.save!

story17 = Story.new(category: "General", title: "The New Wave in Floral Arrangements
", author_id: user5.id, body: "<p>Spiked Bismarck palm fronds, dramatic clusters of ­flamingo-pink anthuriums, flowering quince branches — MetaFlora’s bold arrangements are unexpected and irreverent, marrying ikebana-inflected minimalism with a dash of kitsch. Founder Marisa Competello, a former fashion stylist, constructs her sculptural compositions — which she often coats in layers of spray paint — from her Chinatown studio in Manhattan. ‘‘My work is an overdose of the ’80s,’’ she says.

Competello is one of the highly individual, personality-­driven floral designers who are pushing the craft in new directions. Rather than fetishizing a particular flower or color, their focus is on composition — the more distinctive, the better — a clear departure from the tidy, symmetrical centerpieces that defined the early 2000s floral aesthetic. Their styles may differ wildly — spare and undone, Pop Arty and daring, or wild and painterly — but along with form, the thing that unites these young designers is the depth of inspiration they find in the palette, mood and proportions of work by painters and graphic artists.

Competello’s arrangements, for example, recall the loud, neon-pastel prints of Patrick Nagel — an ­era-of-excess maximalist who created racy illustrations for Playboy, new-wave Duran Duran album covers and winking Budweiser ads. Like Nagel’s cartoonish, color-blocked illustrations, the 40-year-old’s work has a defiantly unnatural ­quality: Monstera leaves are snipped into blunt geometric shapes with scissors and palms are spotted with purple polka dots; entire bouquets are painted cornflower blue or chalk white. ‘‘I am into things that don’t look like flowers — hardy, tropical, sexy plants,’’ she says.</p>")

file = File.open('app/assets/images/floral.jpg')
story17.image = file 
story17.save!
